name: 'Setup Docfx'
description: 'Install docfx in your ubuntu machine'
runs:
  using: "composite"
  steps:
  
    - name: Install mono
      shell: bash
      run: |
        sudo apt install gnupg ca-certificates
        sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
        echo "deb https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
        sudo apt update
        sudo apt install mono-devel
        
    - name: Install docfx
      shell: bash
      run: |
        sudo apt install -y unzip
        wget https://github.com/dotnet/docfx/releases/download/v2.56.6/docfx.zip
        sudo unzip docfx.zip -d /usr/local/docfx
        rm -rf docfx.zip
     
    - name: Create script
      shell: bash
      run: |
        echo 'mono /usr/local/docfx/docfx.exe $@' | sudo tee /usr/local/bin/docfx
        sudo chmod ugo+x /usr/local/bin/docfx
        
