name: 'Setup Docfx'
description: 'Install docfx in your ubuntu machine'
runs:
  using: "composite"
  steps:
    - uses: MirageNet/setup-mono
    
    - name: Install docfx
      shell: bash
      run: |
        sudo apt install -y unzip
        wget https://github.com/dotnet/docfx/releases/download/v2.56.6/docfx.zip
        sudo unzip docfx.zip -d /usr/local/docfx
        rm -rf docfx.zip
     
    - name: Create script
      shell: bash
      run: |
        echo 'mono /usr/local/docfx.exe $@' | sudo tee /usr/local/bin/docfx
        chmod ugo+x /usr/local/bin/docfx
        
