name: 'Setup Docfx'
description: 'Install docfx in ubuntu 18.04'
runs:
  using: "composite"
  steps:
    - name: Install mono
      shell: bash
      run: |
        apt-get install -y gnupg ca-certificates
        apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
        echo "deb https://download.mono-project.com/repo/ubuntu stable-bionic main" | tee /etc/apt/sources.list.d/mono-official-stable.list
        apt-get update
        apt-get install -y mono-devel

    - name: Install docfx
      shell: bash
      run: |
        apt-get install -y unzip
        wget https://github.com/dotnet/docfx/releases/download/v2.56.6/docfx.zip
        unzip docfx.zip -d /usr/local/docfx
        rm -rf docfx.zip

    - name: Create script
      shell: bash
      run: |
        echo 'mono /usr/local/docfx/docfx.exe $@' | tee /usr/local/bin/docfx
        chmod ugo+x /usr/local/bin/docfx
        
